### ISSUE TITLE
_disableInitializers is missing in Bridge’s constructor

### ISSUE THREAD

**Issue by ptisserand** [ArkProjectNFTs/bridge#225]
From https://codehawks.cyfrin.io/c/2024-07-ark-project/s/181

## Summary
`disableinitializers` is not called in Starklane’s constructor

## details
An uninitialized contract can be taken over by an attacker. This applies to both a proxy and its implementation contract, which may impact the proxy. But in the case of the implementation contract, a `disableinitializers()` is necessary to be called in the constructor. This is because when the Bridge contract is deployed and initialized, the initialize method on the newly created proxy's implementation contract is never called. As such, anyone can call that method and pass in whatever values they want as arguments

Unit test must be provided.

**Comment by od-hunter** [comment]
Can I be assigned when od hack starts please! @ptisserand

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I will resolve this issue by taking the following approach:

1. **Adding `_disableInitializers()` to the Bridge Constructor:**
   - The main issue here is that the Bridge contract’s implementation is vulnerable to being initialized multiple times, allowing potential attackers to exploit this. To fix this, I will add a constructor to the Bridge contract that calls `_disableInitializers()`, ensuring that the contract can only be initialized once.
   
   Example:
   ```solidity
   constructor() {
       _disableInitializers();
   }
   ```

   This will ensure that the implementation contract is protected from further initialization once it is deployed.

2. **Reviewing Starklane and Bridge Contracts:**
   - I will review the existing implementation of both the Bridge and Starklane contracts to ensure that this issue doesn't exist elsewhere.
   - I will verify that `_disableInitializers()` is called in any other contract that is deployed via a proxy to avoid similar vulnerabilities.

3. **Writing Unit Tests:**
   - To prevent regressions and validate this fix, I will implement unit tests that check whether the constructor correctly disables initializers. 
   - Specifically, I will test that:
     - After deploying the Bridge contract, any subsequent calls to `initialize()` should revert.
     - I will simulate an attacker trying to call `initialize()` and confirm that they are unable to pass arbitrary arguments due to `_disableInitializers()` being triggered.

   Example test case:
   ```solidity
   function testCannotInitializeAfterDeployment() public {
       vm.expectRevert("Initializers are disabled");
       bridge.initialize(/* malicious arguments */);
   }
   ```

4. **Manual and Automated Testing:**
   - After making the changes, I will manually verify that the vulnerability is fixed by interacting with the contract and ensuring no unauthorized initializations can occur.
   - I will also add the new unit tests to the project’s CI pipeline to guarantee that future updates don’t reintroduce this issue.

By following these steps, I’ll make sure the Bridge contract is protected against unauthorized initialization, and I will ensure that robust tests are in place to confirm the fix.
ETA - 3 days

**Comment by aji70** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
i'm a solidity and cairo smart contract  developer with over 2 years experience and believe i have the skill set for the task and i am also very good with smart contract testing

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I'm a Solidity adn cairo developer specializing in NFT marketplaces and decentralized apps, with experience in multi-token support and integrating blockchain protocols. My work on projects like Worldcoin-Bridge-Linea equips me to handle tasks like adding ERC-20 support efficiently.

### How I plan on tackling this issue
To handle the missing `_disableInitializers` in the Bridge’s constructor:
1. Add `_disableInitializers()`** call in the Bridge constructor to prevent unauthorized initialization.
2. Ensure that this is done before any other logic to secure the contract from potential attacks.
3. **Write unit tests** to confirm that the function is correctly called and that the contract cannot be initialized after deployment.

**Comment by ptisserand** [comment]
Hi @PoulavBhowmick03 any update on this ?

**Comment by PoulavBhowmick03** [comment]
> Hi @PoulavBhowmick03 any update on this ?

hey i will get it done by tonight

**Comment by SoarinSkySagar** [comment]
### My Background
GM, I am a smart contract developer with a focus on writing secure contracts and have been writing contracts in Solidity for 2 years. I have also contributed to the bridge repo before, on https://github.com/ArkProjectNFTs/bridge/pull/235. This task is pretty straightforward and here is how I would approach this issue:

### My Approach
I will import the `Initializable.sol` contract from openzeppelin and make the Starklane contract initializable. Then, I would add the constructor to disable the initializer like this:
```
constructor() {
        _disableInitializers();
}
```
After that, I will write the corresponding unit test and make sure that everything runs and passes the test.

### Docs references
[What does `_disableInitializers();` function mean?](https://forum.openzeppelin.com/t/what-does-disableinitializers-function-mean/28730)

### ETA: 1 Day

**Comment by DanielEmmanuel1** [comment]
Hi @ptisserand @PoulavBhowmick03 Can i please get assigned this issue?
I would love the opportunity to tackle it

**Comment by ptisserand** [comment]
@SoarinSkySagar reassigned to you

**Comment by DanielEmmanuel1** [comment]
Thanks @ptisserand I'll get on it

**Comment by SoarinSkySagar** [comment]
> @SoarinSkySagar reassigned to you

Thank you @ptisserand 🎉
